/** Common English book aliases → slug used in our data. */
const BOOK_ALIASES: Record<string, string> = {
  genesis: "genesis",
  gen: "genesis",
  ge: "genesis",
  gn: "genesis",
  exodus: "exodus",
  exo: "exodus",
  ex: "exodus",
  leviticus: "leviticus",
  lev: "leviticus",
  le: "leviticus",
  numbers: "numbers",
  num: "numbers",
  nu: "numbers",
  nm: "numbers",
  deuteronomy: "deuteronomy",
  deut: "deuteronomy",
  de: "deuteronomy",
  dt: "deuteronomy",
  joshua: "joshua",
  josh: "joshua",
  jos: "joshua",
  judges: "judges",
  judg: "judges",
  jdg: "judges",
  ruth: "ruth",
  ru: "ruth",
  "1 samuel": "1-samuel",
  "1samuel": "1-samuel",
  "1 sam": "1-samuel",
  "1sam": "1-samuel",
  "1sa": "1-samuel",
  "2 samuel": "2-samuel",
  "2samuel": "2-samuel",
  "2 sam": "2-samuel",
  "2sam": "2-samuel",
  "2sa": "2-samuel",
  "1 kings": "1-kings",
  "1kings": "1-kings",
  "1ki": "1-kings",
  "2 kings": "2-kings",
  "2kings": "2-kings",
  "2ki": "2-kings",
  "1 chronicles": "1-chronicles",
  "1chronicles": "1-chronicles",
  "1 chron": "1-chronicles",
  "1ch": "1-chronicles",
  "2 chronicles": "2-chronicles",
  "2chronicles": "2-chronicles",
  "2 chron": "2-chronicles",
  "2ch": "2-chronicles",
  ezra: "ezra",
  ezr: "ezra",
  nehemiah: "nehemiah",
  neh: "nehemiah",
  ne: "nehemiah",
  esther: "esther",
  est: "esther",
  es: "esther",
  job: "job",
  psalms: "psalms",
  psalm: "psalms",
  psa: "psalms",
  ps: "psalms",
  proverbs: "proverbs",
  prov: "proverbs",
  pr: "proverbs",
  prv: "proverbs",
  ecclesiastes: "ecclesiastes",
  eccles: "ecclesiastes",
  ecc: "ecclesiastes",
  ec: "ecclesiastes",
  "song of solomon": "song-of-solomon",
  "song of songs": "song-of-solomon",
  songs: "song-of-solomon",
  sos: "song-of-solomon",
  ss: "song-of-solomon",
  isaiah: "isaiah",
  isa: "isaiah",
  is: "isaiah",
  jeremiah: "jeremiah",
  jer: "jeremiah",
  je: "jeremiah",
  lamentations: "lamentations",
  lam: "lamentations",
  la: "lamentations",
  ezekiel: "ezekiel",
  ezek: "ezekiel",
  eze: "ezekiel",
  daniel: "daniel",
  dan: "daniel",
  da: "daniel",
  hosea: "hosea",
  hos: "hosea",
  ho: "hosea",
  joel: "joel",
  joe: "joel",
  amos: "amos",
  am: "amos",
  obadiah: "obadiah",
  obad: "obadiah",
  ob: "obadiah",
  jonah: "jonah",
  jon: "jonah",
  micah: "micah",
  mic: "micah",
  nahum: "nahum",
  nah: "nahum",
  na: "nahum",
  habakkuk: "habakkuk",
  hab: "habakkuk",
  zephaniah: "zephaniah",
  zeph: "zephaniah",
  zep: "zephaniah",
  haggai: "haggai",
  hag: "haggai",
  hg: "haggai",
  zechariah: "zechariah",
  zech: "zechariah",
  zec: "zechariah",
  malachi: "malachi",
  mal: "malachi",
  matthew: "matthew",
  matt: "matthew",
  mt: "matthew",
  mark: "mark",
  mrk: "mark",
  mk: "mark",
  luke: "luke",
  luk: "luke",
  lk: "luke",
  john: "john",
  jhn: "john",
  jn: "john",
  acts: "acts",
  act: "acts",
  ac: "acts",
  romans: "romans",
  rom: "romans",
  ro: "romans",
  "1 corinthians": "1-corinthians",
  "1corinthians": "1-corinthians",
  "1 cor": "1-corinthians",
  "1cor": "1-corinthians",
  "1co": "1-corinthians",
  "2 corinthians": "2-corinthians",
  "2corinthians": "2-corinthians",
  "2 cor": "2-corinthians",
  "2cor": "2-corinthians",
  "2co": "2-corinthians",
  galatians: "galatians",
  gal: "galatians",
  ga: "galatians",
  ephesians: "ephesians",
  eph: "ephesians",
  philippians: "philippians",
  phil: "philippians",
  php: "philippians",
  colossians: "colossians",
  col: "colossians",
  "1 thessalonians": "1-thessalonians",
  "1thessalonians": "1-thessalonians",
  "1 thess": "1-thessalonians",
  "1th": "1-thessalonians",
  "2 thessalonians": "2-thessalonians",
  "2thessalonians": "2-thessalonians",
  "2 thess": "2-thessalonians",
  "2th": "2-thessalonians",
  "1 timothy": "1-timothy",
  "1timothy": "1-timothy",
  "1 tim": "1-timothy",
  "1ti": "1-timothy",
  "2 timothy": "2-timothy",
  "2timothy": "2-timothy",
  "2 tim": "2-timothy",
  "2ti": "2-timothy",
  titus: "titus",
  tit: "titus",
  philemon: "philemon",
  phlm: "philemon",
  phm: "philemon",
  hebrews: "hebrews",
  heb: "hebrews",
  james: "james",
  jas: "james",
  jm: "james",
  "1 peter": "1-peter",
  "1peter": "1-peter",
  "1 pet": "1-peter",
  "1pe": "1-peter",
  "2 peter": "2-peter",
  "2peter": "2-peter",
  "2 pet": "2-peter",
  "2pe": "2-peter",
  "1 john": "1-john",
  "1john": "1-john",
  "1 jn": "1-john",
  "1jn": "1-john",
  "2 john": "2-john",
  "2john": "2-john",
  "2 jn": "2-john",
  "2jn": "2-john",
  "3 john": "3-john",
  "3john": "3-john",
  "3 jn": "3-john",
  "3jn": "3-john",
  jude: "jude",
  jud: "jude",
  revelation: "revelation",
  rev: "revelation",
  re: "revelation",
};

export type ParsedReference = {
  slug: string;
  chapter: number;
  verse?: number;
};

/**
 * Parse strings like "John 3:16", "Ps 23", "1 Cor 13:4".
 * Returns null if the query does not look like a reference.
 */
export function parseReference(query: string): ParsedReference | null {
  const q = query.trim().toLowerCase().replace(/\s+/g, " ");
  if (!q) return null;

  const match = q.match(
    /^((?:\d\s*)?[a-z][a-z\s]*?)\s+(\d+)(?:\s*[:.]\s*(\d+))?$/i,
  );
  if (!match) return null;

  const bookRaw = match[1].replace(/\s+/g, " ").trim();
  const compact = bookRaw.replace(/\s+/g, "");
  const slug =
    BOOK_ALIASES[bookRaw] ??
    BOOK_ALIASES[compact] ??
    (bookRaw.includes(" ") ? null : BOOK_ALIASES[bookRaw]);

  if (!slug) return null;

  const chapter = Number(match[2]);
  const verse = match[3] ? Number(match[3]) : undefined;
  if (!Number.isFinite(chapter) || chapter < 1) return null;
  if (verse !== undefined && (!Number.isFinite(verse) || verse < 1)) return null;

  return { slug, chapter, verse };
}
